name: rootfs build

on:
  workflow_dispatch:
  

permissions:
  contents: write

jobs:

  build:
  
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Download rootfs and unpack
      run: |
        wget -q https://github.com/termux/proot-distro/releases/download/v4.18.0/ubuntu-noble-aarch64-pd-v4.18.0.tar.xz -P $GITHUB_WORKSPACE/
        sudo tar -xJf ubuntu-noble-aarch64-pd-v4.18.0.tar.xz
        mv ubuntu-noble-aarch64 portadesx-2404
    - name: chroot and update installed rootfs package
      run: |
        sudo mount --bind /proc $GITHUB_WORKSPACE/portadesx-2404/proc
        sudo mount --bind /sys $GITHUB_WORKSPACE/portadesx-2404/sys
        sudo mount --bind /dev $GITHUB_WORKSPACE/portadesx-2404/dev
        sudo mount --bind /dev/pts $GITHUB_WORKSPACE/portadesx-2404/dev/pts
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash
        apt update
#        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "apt update && apt upgrade -y"
#    - name: Install XFCE desktop and basic utility
#      run: |
#        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "apt install xfce4 xfce4-terminal tigervnc-standalone-server dbus-x11 pulseaudio nano wget curl sudo adduser -y && apt clean"
        
      
        
