name: Auto-Build

on:
  workflow_dispatch:
  

permissions:
  contents: write

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download rootfs and unpack
      run: |
        wget -q https://github.com/termux/proot-distro/releases/download/v4.18.0/ubuntu-noble-aarch64-pd-v4.18.0.tar.xz -P $GITHUB_WORKSPACE/
        tar -xJf ubuntu-noble-aarch64-pd-v4.18.0.tar.xz
        mv ubuntu-noble-aarch64 portadesq-2404
    - name: chroot and install depedency
      run: |
        sudo chroot portadesq-2404 -c "apt update && apt upgrade -y"
