name: rootfs build

on:
  workflow_dispatch:
  

permissions:
  contents: write

jobs:

  rootfs-build:
  
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Download rootfs and unpack
      run: |
        wget -q https://github.com/termux/proot-distro/releases/download/v4.18.0/ubuntu-noble-aarch64-pd-v4.18.0.tar.xz -P $GITHUB_WORKSPACE/
        sudo tar -xJf ubuntu-noble-aarch64-pd-v4.18.0.tar.xz
        mv ubuntu-noble-aarch64 portadesx-2404
    - name: chroot and update installed rootfs package
      run: |
        sudo mount --bind /proc $GITHUB_WORKSPACE/portadesx-2404/proc
        sudo mount --bind /sys $GITHUB_WORKSPACE/portadesx-2404/sys
        sudo mount --bind /run $GITHUB_WORKSPACE/portadesx-2404/run
        sudo mount --bind /dev $GITHUB_WORKSPACE/portadesx-2404/dev
        sudo mount --bind /dev/pts $GITHUB_WORKSPACE/portadesx-2404/dev/pts
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "apt update && apt upgrade -y"
    - name: Install XFCE desktop and basic utility
      run: |
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "apt install xfce4 xfce4-terminal dbus-x11 pulseaudio nano wget curl sudo adduser -y && apt clean"
    - name: Adding user and password
      run: |
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo adduser --disabled-password --gecos "" portadesx && echo 'portadesx:123' | chpasswd && echo 'portadesx ALL=(ALL:ALL) ALL' >> /etc/sudoers.d/user"
    - name: Remove snap apt override
      run: |
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo add-apt-repository --remove ppa:mozillateam/firefox-next"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo add-apt-repository --remove ppa:mozillateam/thunderbird-next"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo rm /etc/apt/preferences.d/pin-mozilla-ppa"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo rm /etc/apt/preferences.d/pin-thunderbird-ppa"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "wget https://github.com/arfshl/no-snap-on-apt/raw/main/Noble/arm64/setup.sh && sh setup.sh && rm setup.sh"
    - name: Install user apps
      run: | 
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "apt update && apt install firefox vlc thunderbird evince file-roller ristretto gnome-clocks libheif1 webp-pixbuf-loader -y"
    - name: Install Vivaldi browser
      run: | 
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "wget -q https://downloads.vivaldi.com/stable/vivaldi-stable_7.5.3735.58-1_arm64.deb && dpkg -i vivladi*.deb && apt install -f -y && rm vivaldi*.deb"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo sed -i 's|/usr/bin/vivaldi --incognito %U|/usr/bin/vivaldi --incognito --no-sandbox %U|' /usr/share/applications/vivaldi-stable.desktop"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo sed -i 's|/usr/bin/vivaldi %U|/usr/bin/vivaldi --no-sandbox %U|' /usr/share/applications/vivaldi-stable.desktop"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo sed -i 's|/usr/bin/vivaldi --new-window %U|/usr/bin/vivaldi --new-window --no-sandbox %U|' /usr/share/applications/vivaldi-stable.desktop"
    - name: Unmount and repacking rootfs
      run: |
        sudo umount $GITHUB_WORKSPACE/portadesx-2404/proc
        sudo umount $GITHUB_WORKSPACE/portadesx-2404/sys
        sudo umount $GITHUB_WORKSPACE/portadesx-2404/run
        sudo umount $GITHUB_WORKSPACE/portadesx-2404/dev
        sudo umount $GITHUB_WORKSPACE/portadesx-2404/dev/pts
        sudo tar -cJf $GITHUB_WORKSPACE/release/portadesk-2404.tar.xz $GITHUB_WORKSPACE/portadesx-2404
    - name: Release it!
      uses: softprops/action-gh-release@v2
      with:
          tag_name: v24.04
          release_name: Initial beta release
          body: |
            Based on Ubuntu 24.04 LTS
          draft: false
          prerelease: yes
          files: $GITHUB_WORKSPACE/release/portadesk-2404.tar.xz
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
        
  
